name: Deploy

on:
  push: {branches: [main]}
  schedule: [{cron: "15 10 * * *"}]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: Deploy to Observable Cloud
        run: yarn deploy -- --message "$(git log -1 --pretty=%s)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_TOKEN }}
